name: Apollo router
on:
  push:
    branches:
      - master
    paths:
      - "services/apollo-router"
      - ".github/svc-apollo-router.yml"
      - "services/**/*.graphql"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "services/apollo-router"
      - ".github/svc-apollo-router.yml"
      - "services/**/*.graphql"

jobs:
  build-on-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build supergraph
        working-directory: services/apollo-router
        run: sh compose-supergraph.sh
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: services/apollo-router/Dockerfile
          push: false
          build-args: |
            SUPERGRAPH_FILE=services/apollo-router/supergraph.graphql
            ROUTER_CONFIG_FILE=services/apollo-router/router.yaml
  build-and-deploy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: echo "Deploying to production"
